from django.urls import path
from.import views
from .views import *

urlpatterns = [
    path('',views.login,name='login'),
    path('admin_index',views.admin_index,name='admin_index'),
    path('logout/',views.logout,name='logout'),
    path('add_pet_category/', add_pet_category, name='add_pet_category'),
    path('edit_pet_category/', views.edit_pet_category, name='edit_pet_category'),
    path('delete_pet_category/', views.delete_pet_category, name='delete_pet_category'),
    path('edit_pet_subcategory/', views.edit_pet_subcategory, name='edit_pet_subcategory'),
    path('delete_pet-subcategory/', views.delete_pet_subcategory, name='delete_pet_subcategory'),
    path('add_product_category/', views.add_product_category, name='add_product_category'),
    path('add_vaccine/', views.add_vaccine, name='add_vaccine'),
    path('edit_product_category/', views.edit_product_category, name='edit_product_category'),
    path('edit_vaccine/', views.edit_vaccine, name='edit_vaccine'),
    path('deleteproduct_category/', views.delete_product_category, name='delete_product_category'),
    path('delete_vaccine/', views.delete_vaccine, name='delete_vaccine'),
    path('add_products/', views.add_products, name='add_products'),
    path('view_products/', views.view_products, name='view_products'),
    path('view_vaccines/', views.view_vaccines, name='view_vaccines'),
    path('edit_products/', views.edit_products, name='edit_products'),
    path('delete_products/', views.delete_products, name='delete_products'),
    # path('delivery-boys/', views.delivery_boy_list, name='delivery_boy_list'),
    path('delivery-boy/approve/', views.approve_delivery_boy, name='approve_delivery_boy'),
    path('delivery-boy/reject/', views.reject_delivery_boy, name='reject_delivery_boy'),
    path("assign-orders/", views.assign_orders, name="assign_orders"),
    path("assign-orders/<int:order_id>/assign/", views.assign_delivery_agent, name="assign_delivery_agent"),
    path('admin_view_orders/',views.admin_view_orders,name='admin_view_orders'),
    # path('doctor_list/', views.doctor_list, name='doctor_list'),
    path('approve_doctor/', views.approve_doctor, name='approve_doctor'),
    path('reject_doctor/', views.reject_doctor, name='reject_doctor'),
    path('pending_delivery/', pending_delivery_agents, name='pending_delivery_agents'),
    path('approved_delivery/', approved_delivery_agents, name='approved_delivery_agents'),
    path('rejected_delivery/', rejected_delivery_agents, name='rejected_delivery_agents'),
    path('doctors/pending/', pending_doctors, name='pending_doctors'),
    path('doctors/approved/', approved_doctors, name='approved_doctors'),
    path('doctors/rejected/', rejected_doctors, name='rejected_doctors'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/feedback-complaints/', admin_feedback_complaint_view, name='admin_feedback_complaints'),
    path('api/doctor/feedback/', views.get_doctor_feedback, name='get_doctor_feedback'),
    path('api/doctor/feedback/<int:doctor_id>/', views.get_doctor_feedback, name='get_doctor_feedback_by_id'),
    path('api/doctor/complaints/', views.get_doctor_complaints, name='get_doctor_complaints'),
    path('api/doctor/complaints/<int:doctor_id>/', views.get_doctor_complaints, name='get_doctor_complaints_by_id'),
    path('api/doctor/complaint/<int:complaint_id>/update/', views.update_complaint_status, name='update_complaint_status'),
    path('api/doctor/feedback/submit/', views.submit_doctor_feedback, name='submit_doctor_feedback'),
    path('manage_subcategories/', views.manage_subcategories, name='manage_subcategories'),
]
