# Generated by Django 5.1.3 on 2025-10-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='deliveryboys/profile/')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='deliveryboys/id_cards/')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
