# Generated by Django 5.2.10 on 2026-02-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether agent is currently available for deliveries'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Agent's current location latitude", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Agent's current location longitude", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='service_radius',
            field=models.IntegerField(default=10, help_text='Service radius in kilometers'),
        ),
    ]
