# Generated by Django 5.2.10 on 2026-02-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_remove_deliveryagent_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='place',
            field=models.CharField(choices=[('thrissur', 'Thrissur'), ('kunnamkulam', 'Kunnamkulam'), ('chalakkudy', 'Chalakkudy'), ('kodungallur', 'Kodungallur'), ('guruvayur', 'Guruvayur'), ('iriyur', 'Iriyur'), ('cholapuram', 'Cholapuram'), ('elavally', 'Elavally'), ('karumathra', 'Karumathra'), ('kattakampal', 'Kattakampal'), ('manalur', 'Manalur'), ('minalur', 'Minalur'), ('mullassery', 'Mullassery'), ('nadathara', 'Nadathara'), ('naduvil', 'Naduvil'), ('nellayi', 'Nellayi'), ('ollur', 'Ollur'), ('panamkutty', 'Panamkutty'), ('pandipulam', 'Pandipulam'), ('parappukkara', 'Parappukkara'), ('peedika', 'Peedika'), ('perakam', 'Perakam'), ('perumannur', 'Perumannur'), ('pullazhi', 'Pullazhi'), ('puthenchira', 'Puthenchira'), ('thangalur', 'Thangalur'), ('thayyur', 'Thayyur'), ('thiruvilwamala', 'Thiruvilwamala'), ('thozhiyur', 'Thozhiyur'), ('velur', 'Velur'), ('venmanad', 'Venmanad')], default='thrissur', help_text='Place in Thrissur district', max_length=50),
        ),
    ]
