# Generated by Django 5.2.10 on 2026-02-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0005_alter_deliveryagent_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='longitude',
        ),
    ]
