# Generated by Django 5.1.3 on 2025-10-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='petcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.petcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='petsubcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.petsubcategory'),
            preserve_default=False,
        ),
    ]
