# Generated by Django 5.1.3 on 2025-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
