# Generated by Django 5.1.3 on 2025-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_image_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_pets',
            field=models.IntegerField(default=0),
        ),
    ]
