# Generated by Django 5.1.3 on 2025-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_cart_productbooking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
