# Generated by Django 5.1.3 on 2025-10-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_productbooking_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
