# Generated by Django 5.1.3 on 2025-10-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
        ('doctorapp', '0003_doctor_status_timeslot'),
        ('userapp', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order', to='deliveryapp.deliveryagent'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('Vaccine', 'Vaccine'), ('Routine checkup', 'Routine checkup'), ('Sickness', 'Sickness')], max_length=50)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pet')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.timeslot')),
            ],
            options={
                'unique_together': {('doctor', 'slot', 'date')},
            },
        ),
    ]
