# Generated by Django 5.2.10 on 2026-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_user_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(choices=[('thrissur', 'Thrissur'), ('tvm', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pathanamthitta', 'Pathanamthitta'), ('alappuzha', 'Alappuzha'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasargod', 'Kasaragod')], default='thrissur', help_text='District as place', max_length=50),
        ),
    ]
