# Generated by Django 5.2.10 on 2026-02-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_alter_user_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
