# Generated by Django 5.1.3 on 2025-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
    ]
