# Generated by Django 5.2.10 on 2026-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='additional_medication_notes',
            field=models.TextField(blank=True, help_text='Any additional medication instructions', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='days_duration',
            field=models.PositiveIntegerField(default=7, help_text='For how many days'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='As prescribed', help_text='e.g., 500mg, 5ml, 1 tablet', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='food_timing',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('anytime', 'Anytime')], default='anytime', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='Twice daily', help_text='e.g., Twice daily, Once daily', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_name',
            field=models.CharField(default='Not specified', help_text='Name of medication', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('noon', 'Noon'), ('evening', 'Evening'), ('night', 'Night'), ('morning_night', 'Morning & Night'), ('all', 'All times (Morning, Noon, Evening, Night)')], default='morning_night', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(help_text='General care instructions for pet owner'),
        ),
    ]
