# Generated by Django 5.2.10 on 2026-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0007_remove_prescription_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='additional_medication_notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='follow_up_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='food_timing',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(default=list, help_text='List of medications, each with name, dosage, food_timing, time_of_day'),
        ),
    ]
