# Generated by Django 5.2.10 on 2026-02-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0008_remove_prescription_additional_medication_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_slots', to='doctorapp.doctor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_dates', to='doctorapp.timeslot')),
            ],
            options={
                'unique_together': {('doctor', 'slot', 'date')},
            },
        ),
    ]
